GET http://localhost:8080/authorize?user=admin&password=1111
Accept: application/json

###

GET http://localhost:8080/authorize?user=manager&password=2222
Accept: application/json

###

GET http://localhost:8080/authorize?user=user&password=3333
Accept: application/json

###

GET http://localhost:8080/authorize?user=&password=1111
Accept: application/json

###

GET http://localhost:8080/authorize?user=petya&password=1111
Accept: application/json

###
